<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Run on Firefox"
           tests="2"
           failures="2"
           errors="0"
           skipped="0"
           time="0.599">
  <properties />
            <testcase name="Register_01_Empty_Data_Fail_Veryfy" time="0.493" classname="com_nopcommerce_account.Level_17_ReportNG">
                <failure type="java.lang.Throwable"
                  message="Multiple failures (2):
Failure 1 of 2
java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at org.testng.Assert.assertFalse(Assert.java:89)
	at commons.BaseTest.verifyFalse(BaseTest.java:122)
	at com_nopcommerce_account.Level_17_ReportNG.Register_01_Empty_Data_Fail_Veryfy(Level_17_ReportNG.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:819)
	at org.testng.TestRunner.run(TestRunner.java:619)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)

Failure 2 of 2
java.lang.AssertionError: expected [Điều khoản dịch vụ sadjfk] but found [Điều khoản dịch vụ]"
              >
<![CDATA[java.lang.Throwable: Multiple failures (2):
Failure 1 of 2
java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertFalse(Assert.java:79)
	at org.testng.Assert.assertFalse(Assert.java:89)
	at commons.BaseTest.verifyFalse(BaseTest.java:122)
	at com_nopcommerce_account.Level_17_ReportNG.Register_01_Empty_Data_Fail_Veryfy(Level_17_ReportNG.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:819)
	at org.testng.TestRunner.run(TestRunner.java:619)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)

Failure 2 of 2
java.lang.AssertionError: expected [Điều khoản dịch vụ sadjfk] but found [Điều khoản dịch vụ]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1578)
  org.testng.Assert.assertEqualsImpl(Assert.java:150)
  org.testng.Assert.assertEquals(Assert.java:132)
  org.testng.Assert.assertEquals(Assert.java:644)
  commons.BaseTest.verifyEquals(BaseTest.java:138)
  com_nopcommerce_account.Level_17_ReportNG.Register_01_Empty_Data_Fail_Veryfy(Level_17_ReportNG.java:57)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:819)
  org.testng.TestRunner.run(TestRunner.java:619)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
  org.testng.SuiteRunner.run(SuiteRunner.java:336)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
  org.testng.TestNG.runSuites(TestNG.java:1134)
  org.testng.TestNG.run(TestNG.java:1101)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
      </failure>

          </testcase>
            <testcase name="Register_02_Empty_Data_Fail_Assert" time="0.106" classname="com_nopcommerce_account.Level_17_ReportNG">
                <failure type="java.lang.AssertionError"
                  message="expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: expected [false] but found [true]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1578)
  org.testng.Assert.assertFalse(Assert.java:79)
  org.testng.Assert.assertFalse(Assert.java:89)
  com_nopcommerce_account.Level_17_ReportNG.Register_02_Empty_Data_Fail_Assert(Level_17_ReportNG.java:74)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:819)
  org.testng.TestRunner.run(TestRunner.java:619)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
  org.testng.SuiteRunner.run(SuiteRunner.java:336)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
  org.testng.TestNG.runSuites(TestNG.java:1134)
  org.testng.TestNG.run(TestNG.java:1101)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
